version: '2.2'
services:
    polis:
        build: .
        image: polis:1.6.5
        environment:
            - SENTINEL_CONFIG=/var/sentinel/sentinel.conf
        volumes:
            - ./polis:/var/polis
            - ./sentinel:/var/sentinel
        ports:
          - 24126:24126
        restart: unless-stopped
        cpus: 1.0
